"""empty message

Revision ID: 5a63fda7d3de
Revises: None
Create Date: 2016-05-27 21:00:01.168158

"""

# revision identifiers, used by Alembic.
revision = '5a63fda7d3de'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('reading_day', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_reading')
    ### end Alembic commands ###
